export const promotions = [
  {
    id: "0001",
    title: "Happy hoy",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 30,
    colors: ["white"],
    sizes: ["10", "12", "14"],
    categories: ["inicial"],
    image: "/phone.png",
    createdAt: "10/12/2023",
  },
  {
    id: "0001",
    title: "Tomahawk",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 150,
    colors: ["white"],
    sizes: ["S", "M", "L"],
    categories: ["secundaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
  },
  {
    id: "0002",
    title: "Pollo a la parrilla + cerveza artesanal",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 40,
    colors: ["white"],
    sizes: ["12", "14", "S", "M"],
    categories: ["primaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
  },
];
