export const promotions = [
  {
    id: "0001",
    title: "Happy hoy",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 30,
    colors: ["white"],
    sizes: ["10", "12", "14"],
    categories: ["inicial"],
    image: "/phone.png",
    createdAt: "10/12/2023",
  },
  {
    id: "0001",
    title: "Tomahawk",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 150,
    colors: ["white"],
    sizes: ["S", "M", "L"],
    categories: ["secundaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
  },
  {
    id: "0002",
    title: "Pollo a la parrilla + cerveza artesanal",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 40,
    colors: ["white"],
    sizes: ["12", "14", "S", "M"],
    categories: ["primaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
  },
];

export const products = [
  {
    id: "0001",
    title: "Producto 1",
    desc: "Lorem ipsun",
    price: "12",
    category: "Parrillas",
    image: "/phone.png",
  },
  {
    id: "0002",
    title: "Producto 2",
    desc: "Lorem ipsun",
    price: "13",
    category: "Carnes",
    image: "/phone.png",
  },
  {
    id: "0003",
    title: "Producto 3",
    desc: "Lorem ipsun",
    price: "14",
    category: "Mixtos",
    image: "/phone.png",
  },
  {
    id: "0004",
    title: "Producto 4",
    desc: "Lorem ipsun",
    price: "14",
    category: "Panes",
    image: "/phone.png",
  },
  {
    id: "0005",
    title: "Producto 5",
    desc: "Lorem ipsun",
    price: "14",
    category: "Tomahawks",
    image: "/phone.png",
  },
  {
    id: "0006",
    title: "Producto 6",
    desc: "Lorem ipsun",
    price: "14",
    category: "Guarniciones",
    image: "/phone.png",
  },
];
